# Generated by Django 3.2.4 on 2021-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210609_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='default')),
            ],
        ),
    ]
