# Generated by Django 3.2.4 on 2021-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_defaultpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=False, null=True, upload_to='profile_photos'),
        ),
    ]
